version: '3'
services:
    mongo-cnf-2:
        container_name: "mongo-cnf-2"
        image: mongo:4.0.1
        ports:
            - "30102:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        restart: always
        networks:
            my_network:
                aliases:
                    - mongo-cnf-2
        healthcheck:
            test: [ "CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 5s
            retries: 5

    mongo-cnf-3:
        container_name: "mongo-cnf-3"
        image: mongo:4.0.1
        ports:
            - "30103:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        restart: always
        networks:
            my_network:
                aliases:
                    - mongo-cnf-3
        healthcheck:
            test: [ "CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 5s
            retries: 5

    mongo-cnf-1:
        container_name: "mongo-cnf-1"
        image: mongo:4.0.1
        ports:
            - "30101:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        restart: always
        networks:
            my_network:
                aliases:
                    - mongo-cnf-1
        healthcheck:
            test: [ "CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 5s
            retries: 5

    mongo-cnf-setup:
        container_name: "mongo-cnf-setup"
        image: mongo:4.0.1
        depends_on:
            - "mongo-cnf-1"
            - "mongo-cnf-2"
            - "mongo-cnf-3"
        links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-cnf-1
            - MONGO2=mongo-cnf-2
            - MONGO3=mongo-cnf-3
            - RS=cnf-serv
            - PORT=27017
        entrypoint: [ "/scripts/setup-cnf.sh" ]
        networks:
            my_network:
                aliases:
                    - mongo-cnf-setup

networks:
    my_network:
        driver: bridge
